### ISSUE TITLE
Multiple rares throughout zones maybe a QoL

### ISSUE THREAD

**Issue by Take1hat** [Take1hat/Bug-tracker-for-WOD#27]
## What is the Bug? (Brief Overview)
Rares are not so rare
## Expected Behavior
Rares sometime having hours of respawns and only being 1 instead of multiple

## Current Behavior
Multiple rares

## Steps to Reproduce

1. Find a rare
2. Find another rare
3. ???
4. Profit

## Attach a Video Link or Screenshot
https://user-images.githubusercontent.com/105388656/167979100-4ef4fc59-f4e3-410a-8c22-dc0847a64ee6.png

**Comment by Alleujah** [comment]
Found and deleted.
