### ISSUE TITLE
Tons of duplicate NPCs in Kezan, incorrect phase IDs.

### ISSUE THREAD

**Issue by Take1hat** [Take1hat/Bug-tracker-for-WOD#4]
## What is the Bug? (Brief Overview)
All across the island of Kezan you'll find duplicate NPCs, or NPCs that you aren't supposed to see until later in the questline. Can't realistically write an issue for every single NPC, but all of these need to be set to certain phasemasks.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Alleujah** [comment]
This is a part of a larger problem.
May have Goblins and Worgens start in capital cities as level 10 and green gear.
- phasing needs to be addressed.
