### ISSUE TITLE
Player starts in the wrong terrain phase of Gilneas, Worgen starting zone.

### ISSUE THREAD

**Issue by Take1hat** [Take1hat/Bug-tracker-for-WOD#5]
## What is the Bug? (Brief Overview)
When creating a Worgen, you start off in the city. However, the city here is already ruined with the gates open. The player needs to begin in the terrain phase where the city is still perfectly intact.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Alleujah** [comment]
This is a part of a larger problem. 
May have Goblins and Worgens start in capital cities as level 10 and green gear. 
- phasing needs to be addressed.

**Comment by Alleujah** [comment]
This is a part of a larger problem.
May have Goblins and Worgens start in capital cities as level 10 and green gear.
- phasing needs to be addressed.
